### PR TITLE
Rewrite agora

### PR DESCRIPTION
**Pull request by Nautman**
This is the branch with work for Agora.

### CODE REVIEW

**Comment by Zigolox** [comment]
- [ ] One should not be able to star when not logged in
- [ ]  Feed should be moved to the side and a post button should exist
- [ ]  Colors for comment indentation? Config?
- [ ]  Markdown?
- [ ] Editing posts and comments?
- [ ] Agora button placement?
- [ ] Share button, report button and comment must be fixed.
- [ ] Instead of drop down menu with two choices consider separate buttons.
- [ ] Translate phrases.

**Comment by Nautman** [comment]
I think this PR is an MVP at the moment. To my knowledge, there should only be a couple of things done:

- [ ] design fixes
- [ ] UI improvements (loading animation for comments & material-ui report dialog )
- [ ] translations

I'm marking this as ready for review as I would like your comments at this stage.

Please contact me if you would like me to send an IP where I currently host the server (so you don't have to build it yourself).

**Comment by Zigolox** [comment]
- [ ] The explanation box should look more like the old one
image
image 

- [ ]  The explanation should also be aligned with posts height. 
image

- [ ] Date should show after 30 day
image

- [ ] The whole posts should light up when selecting a post like the old version. 

- [ ] The whole post should pressable not only the title like the old version.

- [ ] general should not be capitalized when viewing comments
image
image

- [ ] The current hypagora should show?
image

- [ ] Tags should be rendered

- [ ] Profile picture should be clickable

- [ ] Name color should render

- [ ] When loading in an agoragram the loading post is smaller than the real post by some pixels

- [ ] When on an agoragram one should be able to click the background to return to the same place on general

- [ ] The text/link most be bigger on link-posts and elips for link

- [ ] Image if no content was found
image

- [ ] It should not be able to publish a comment without body

- [ ] It should be written if a post was edited

- [ ] Save and cancel button should have icons when editing

- [ ] The date should adjustable for Top shorted

- [ ] Delete button needs conformation. "Are you sure?" message


### Discussion
How big should the username be? Some forums have focus on the name and therefor the

**Comment by jugswe** [comment]
- [ ] Editable tags?

**Comment by Nautman** [comment]
This is good enough. We need to start updating for the new API rewrite.

**Pull request merged**
