### PR TITLE
Settings page for rewrite

### PR DESCRIPTION
**Pull request by Nautman**
This is for issue #42.

Currently you can change your name, username, gender, birthdate and password.

This is a draft pull request, since it is not completed.

### CODE REVIEW

**Comment by Nautman** [comment]
Here is a sneak peak of the basic profile card. It is found in the above commit.

Dark             |  Light
:-------------------------:|:-------------------------:
  |  
 | 
Screenshot 2020-06-23 at 23 23 15 | Screenshot 2020-06-23 at 23 23 20

**Comment by Nautman** [comment]
An update on the progress of a color picker. I have focused (maybe a little too much) on the actual radio button for each color. They have a very neat animation.

Light | Dark
----|-----
Screenshot 2020-06-25 at 16 47 58 | Screenshot 2020-06-25 at 16 48 06

**Comment by charlesmaddock** [comment]
Looks marvelous Douglas, great work!

**Comment by Zigolox** [comment]
Great!

**Comment by Nautman** [comment]
Currently waiting on https://github.com/digitalungdom-se/user-api/pull/5 so I can get back birthdate and gender settings as described in the issue linked to this pull request.

**Comment by Nautman** [comment]
I don't think we should wait any longer since the pull request above is closed. We'll have to fix these issues later.

We also need the code from the Agora pull request for working with the redux user slice.

**Pull request merged**
